name: Laravel

on:
  push:
    branches: [ main ]

jobs:
  laravel-pytchou:

    runs-on: self-hosted

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '7.3'
    - uses: actions/checkout@v2
    - name: Install Composer Dependencies
      run: /usr/local/bin/composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Maintenance Mode Up
      run: /usr/bin/php artisan down
    #- name: Install Node JS Dependencies
    #  run: /usr/bin/npm install
    - name: Update Composer Dependencies
      run: /usr/local/bin/composer update
    - name: Update Node JS Dependencies
      run: /usr/bin/npm update
    - name: Copy .env
      run: /usr/bin/php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Generate key
      run: /usr/bin/php artisan key:generate
    #- name: Generate Minify files
     # run: /usr/bin/npm run prod
    - name: Maintenance Mode Down
      run: /usr/bin/php artisan up
